name: js-cli-templates-rif
files:
  - 'bin/*.js'
  - '*'
  - '.*'
  - '!rif.config.yaml'
replacements:
  - from: /js-cli/g
    to: '${PROJECT_NAME}'
  - from: /jsc/g
    to: '${PROJECT_NAME}'
  - from: 'jswork'
    to: 'jswork'
  - from: __USAGE__
    to: $(node bin/index.js -h)
